/* eslint-disable prettier/prettier */
import React from 'react';
import { Box, Button, createTheme, Stack, ThemeProvider, Typography } from '@mui/material';
import Image from 'next/image';
import icon from '../../../../../public/QucikPanel/Downloadresouces/pdf2.png'
import download from '../../../../../public/QucikPanel/Downloadresouces/cdownload.png'
const theme = createTheme({
  typography:{
    fontFamily:`montserrat`
  }
})

const Downloadresources = () => {
  return (
    <div>
      <ThemeProvider theme={theme}>
        <Box padding={`15px`}>
          <Stack spacing={2}>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Portal Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Dashboard Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Common Profile Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Degree Attestation Application Request Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Profile Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Education Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Attestation Details Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Document Upload Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Verify Details Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Forgot Password Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Sign In Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Sign Up Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Cancel Application Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Application Scheduling/Rescheduling Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Revision Requested Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Upload Courier Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Upload Additional Documents Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >DES Profile Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Detail of Degree Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Equivalence Details Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >DES Upload Document Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >DES Verify Details Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >DES User Tasks Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Payment Verification Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >DES Cancel Application</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Foreign DES Profile Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Foreign DES Detail of Degree Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Foreign DES Equivalence Details Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Foreign DES Upload Document Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Foreign DES Verify Details Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Foreign DES User Tasks Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Foreign DES Payment Verification Manual</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
            <Box display={`flex`} alignItems={`center`} justifyContent={`space-between`} padding={`8px 13px`} sx={{bgcolor:`#f7f7f7`, borderRadius:`4px`, border:`1px solid #dedede`}}><Box display={`flex`} alignItems={`center`} ><Image src={icon} alt={`pdf`} ></Image><Typography fontSize={`13px`} fontWeight={700} color={`rgba(51,51,51,.85)!important`} marginLeft={`10px`} >Foreign DES Cancel Application</Typography></Box><Button disableRipple startIcon={<Image src={download} alt={`icon`} />} sx={{color:`#017a37`, fontSize:`13px`, textTransform:`none`, fontWeight:`600`}}>Download</Button></Box>
          </Stack>

        </Box>

      </ThemeProvider>
    </div>
  )
}

export default Downloadresources
